### ISSUE TITLE
How to use the project from the beginning?

### ISSUE THREAD

**Issue by qaz8788817** [NaughtyZZ/3D_facial_shape_attribute_translation_ssgmap#1]
Hi, this is a great project.
And I'm a newbie in this field.
I want to know how to have a output 3D mesh after I trained my model?
Or how to make output.mat into a mesh?

Thank you.

**Comment by NaughtyZZ** [comment]
> Hi, this is a great project. And I'm a newbie in this field. I want to know how to have a output 3D mesh after I trained my model? Or how to make output.mat into a mesh?
> 
> Thank you.

You can run the script “write_data_ply.m” to produce *.ply file and view the file on opensoure softwares such as **meshlab**.

**Comment by qaz8788817** [comment]
Hi, thank you so much for responding to my question.
But I get an error from matlab: 
![image](https://github.com/NaughtyZZ/3D_facial_shape_attribute_translation_ssgmap/assets/73918947/797a9259-0c4e-4127-84d4-40eccf8b9157)

Thanks for your helping!!

**Comment by NaughtyZZ** [comment]
> Hi, thank you so much for responding to my question. But I get an error from matlab: ![image](https://private-user-images.githubusercontent.com/73918947/293637210-797a9259-0c4e-4127-84d4-40eccf8b9157.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzg0ODcsIm5iZiI6MTcwNDE3ODE4NywicGF0aCI6Ii83MzkxODk0Ny8yOTM2MzcyMTAtNzk3YTkyNTktMGM0ZS00MTI3LTg0ZDQtNDBlY2NmOGI5MTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA2NDk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMGE4ZTcxYzA4OWNhNWE1MTc4ZTc1NDM0MTAxMjllZDNiNmVjYmIyZDRjYTlmN2YyNjMyZTIxMjI1OTkxNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WnPdxEcSfXVbf3xGY8Fb9wzF6slEwdzBXvkJyjyb-mw)
> 
> Thanks for your helping!!

The function ‘’VertexNormal may rely on a  [geometry processing library](https://github.com/alecjacobson/gptoolbox/). You can add the dependencies or simply replace the variable 'normal2' by 'normal' to bypass the dependencies for the result.

**Comment by qaz8788817** [comment]
> > Hi, thank you so much for responding to my question. But I get an error from matlab: ![image](https://private-user-images.githubusercontent.com/73918947/293637210-797a9259-0c4e-4127-84d4-40eccf8b9157.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzg0ODcsIm5iZiI6MTcwNDE3ODE4NywicGF0aCI6Ii83MzkxODk0Ny8yOTM2MzcyMTAtNzk3YTkyNTktMGM0ZS00MTI3LTg0ZDQtNDBlY2NmOGI5MTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA2NDk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMGE4ZTcxYzA4OWNhNWE1MTc4ZTc1NDM0MTAxMjllZDNiNmVjYmIyZDRjYTlmN2YyNjMyZTIxMjI1OTkxNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WnPdxEcSfXVbf3xGY8Fb9wzF6slEwdzBXvkJyjyb-mw)
> > Thanks for your helping!!
> 
> The function ‘’VertexNormal may rely on a [geometry processing library](https://github.com/alecjacobson/gptoolbox/). You can add the dependencies or simply replace the variable 'normal2' by 'normal' to bypass the dependencies for the result.

I want to make sure that changing normal2 to normal will not have any impact on subsequent rendering, right?
And this is my "write_data_ply.m" and one of the output ply file: 
![image](https://github.com/NaughtyZZ/3D_facial_shape_attribute_translation_ssgmap/assets/73918947/66f87e26-59dc-4737-b2c8-4083f046d137)
![image](https://github.com/NaughtyZZ/3D_facial_shape_attribute_translation_ssgmap/assets/73918947/9902d456-fa8f-4fd7-a741-5abfac2cc6a4)

Thank you!!!!!

**Comment by NaughtyZZ** [comment]
> > > Hi, thank you so much for responding to my question. But I get an error from matlab: ![image](https://private-user-images.githubusercontent.com/73918947/293637210-797a9259-0c4e-4127-84d4-40eccf8b9157.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzg0ODcsIm5iZiI6MTcwNDE3ODE4NywicGF0aCI6Ii83MzkxODk0Ny8yOTM2MzcyMTAtNzk3YTkyNTktMGM0ZS00MTI3LTg0ZDQtNDBlY2NmOGI5MTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA2NDk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMGE4ZTcxYzA4OWNhNWE1MTc4ZTc1NDM0MTAxMjllZDNiNmVjYmIyZDRjYTlmN2YyNjMyZTIxMjI1OTkxNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WnPdxEcSfXVbf3xGY8Fb9wzF6slEwdzBXvkJyjyb-mw)
> > > Thanks for your helping!!
> > 
> > 
> > The function ‘’VertexNormal may rely on a [geometry processing library](https://github.com/alecjacobson/gptoolbox/). You can add the dependencies or simply replace the variable 'normal2' by 'normal' to bypass the dependencies for the result.
> 
> I want to make sure that changing normal2 to normal will not have any impact on subsequent rendering, right? And this is my "write_data_ply.m" and one of the output ply file: ![image](https://private-user-images.githubusercontent.com/73918947/293647404-66f87e26-59dc-4737-b2c8-4083f046d137.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODI0MjcsIm5iZiI6MTcwNDE4MjEyNywicGF0aCI6Ii83MzkxODk0Ny8yOTM2NDc0MDQtNjZmODdlMjYtNTlkYy00NzM3LWIyYzgtNDA4M2YwNDZkMTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA3NTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YTM5NzU4ZjcyODMyNjgyYmUxYmZmZDk5OWFkNmU1ODIzNWE1MmM3NzIzOGYxYmYwMjQyNDI3MjRmMjhkOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XZnokfhKqntxlnnKWmMCIRP5DFBOwHP5YSCaWd8bsQ8) ![image](https://private-user-images.githubusercontent.com/73918947/293647514-9902d456-fa8f-4fd7-a741-5abfac2cc6a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODI0MjcsIm5iZiI6MTcwNDE4MjEyNywicGF0aCI6Ii83MzkxODk0Ny8yOTM2NDc1MTQtOTkwMmQ0NTYtZmE4Zi00ZmQ3LWE3NDEtNWFiZmFjMmNjNmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA3NTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNmUzZGU5ZGQwNjQ2ZTE0YWMwN2NkMzBiNTdlMWY2ZTk4YmMwNDhmNTZlNTJhYTkxNmFjMjRmNDc1OGZjNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tu5wFyt-zvKGUyrdgAPhMjKAcwQzlwDmLDlHuFviuE4)
> 
> Thank you!!!!!

It will have impact on subsequent rendering. The vertexNormal function is very simple. You may write the vertexNormal function yourself or use the aforementioned library.

**Comment by qaz8788817** [comment]
> > > > Hi, thank you so much for responding to my question. But I get an error from matlab: ![image](https://private-user-images.githubusercontent.com/73918947/293637210-797a9259-0c4e-4127-84d4-40eccf8b9157.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzg0ODcsIm5iZiI6MTcwNDE3ODE4NywicGF0aCI6Ii83MzkxODk0Ny8yOTM2MzcyMTAtNzk3YTkyNTktMGM0ZS00MTI3LTg0ZDQtNDBlY2NmOGI5MTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA2NDk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMGE4ZTcxYzA4OWNhNWE1MTc4ZTc1NDM0MTAxMjllZDNiNmVjYmIyZDRjYTlmN2YyNjMyZTIxMjI1OTkxNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WnPdxEcSfXVbf3xGY8Fb9wzF6slEwdzBXvkJyjyb-mw)
> > > > Thanks for your helping!!
> > > 
> > > 
> > > The function ‘’VertexNormal may rely on a [geometry processing library](https://github.com/alecjacobson/gptoolbox/). You can add the dependencies or simply replace the variable 'normal2' by 'normal' to bypass the dependencies for the result.
> > 
> > 
> > I want to make sure that changing normal2 to normal will not have any impact on subsequent rendering, right? And this is my "write_data_ply.m" and one of the output ply file: ![image](https://private-user-images.githubusercontent.com/73918947/293647404-66f87e26-59dc-4737-b2c8-4083f046d137.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODI0MjcsIm5iZiI6MTcwNDE4MjEyNywicGF0aCI6Ii83MzkxODk0Ny8yOTM2NDc0MDQtNjZmODdlMjYtNTlkYy00NzM3LWIyYzgtNDA4M2YwNDZkMTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA3NTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YTM5NzU4ZjcyODMyNjgyYmUxYmZmZDk5OWFkNmU1ODIzNWE1MmM3NzIzOGYxYmYwMjQyNDI3MjRmMjhkOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XZnokfhKqntxlnnKWmMCIRP5DFBOwHP5YSCaWd8bsQ8) ![image](https://private-user-images.githubusercontent.com/73918947/293647514-9902d456-fa8f-4fd7-a741-5abfac2cc6a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODI0MjcsIm5iZiI6MTcwNDE4MjEyNywicGF0aCI6Ii83MzkxODk0Ny8yOTM2NDc1MTQtOTkwMmQ0NTYtZmE4Zi00ZmQ3LWE3NDEtNWFiZmFjMmNjNmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA3NTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNmUzZGU5ZGQwNjQ2ZTE0YWMwN2NkMzBiNTdlMWY2ZTk4YmMwNDhmNTZlNTJhYTkxNmFjMjRmNDc1OGZjNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tu5wFyt-zvKGUyrdgAPhMjKAcwQzlwDmLDlHuFviuE4)
> > Thank you!!!!!
> 
> It will have impact on subsequent rendering. The vertexNormal function is very simple. You may write the vertexNormal function yourself or use the aforementioned library.

OK!! Very thank you !!!!!!
