### ISSUE TITLE
The details about training data 

### ISSUE THREAD

**Issue by qaz8788817** [NaughtyZZ/3D_facial_shape_attribute_translation_ssgmap#2]
Sorry to bother you again.
I obtained the authorization for the FaceScape data set today and downloaded all the data.
I would like to ask about the internal format of training_data.hdf5 and how the structure inside it classifies data?
And I would also like to ask which section of the paper is "formalize the data with our provided gmap" mentioned in READ.ME? And is there any explanation about this part of the implementation?

I'm sorry and please forgive my stupidity, it's my first time coming into contact with this field, and there is no senior in the same field in the laboratory who can lead me.

**Comment by NaughtyZZ** [comment]
I suggest you can register the raw data using the provided 3D template in the folder './template/'. The 3D template is topological identical to the provided 2D template in the folder  './template/'. Then the data can be converted to Gmap for training by encoding the 'xyz' coodinates of each vertices.  An alternative and simple way to formalize the data with the provided gmap to clip the frontal part of the provide (registered) 'TU models'. I will add a file for the vetex indices for the frontal parts. However, some problematic meshes in the 'TU models' should be excluded or repaired in this way. Therefore, I recommend to register the raw data from scratch, but the process is a bit umbersome. You may refer to the code of my another project for 3D face registration.

**Comment by NaughtyZZ** [comment]
The supplementary material of the paper provides some details.

**Comment by qaz8788817** [comment]
> The supplementary material of the paper provides some details.論文的補充資料提供了一些細節。

Thank you. I will try my best.

**Comment by NaughtyZZ** [comment]
I add the correponding clipped  indices for the TU models in the original FaceScape dataset.

**Comment by qaz8788817** [comment]
Sorry, I have tried all day and spent all time to read and study how to register the model, it still nothing work to me.
There are some things I want to clarify:
1. Does register mean to clip the frontal part from the raw data?
2. In another paper, can I just use the Matlab to register each facial model?
3. Are the landmarks on each facial model marked by human? Or they can be generated by some tools?

Thank you. I hope you don't consider these questions too simplistic; I'll make an effort to learn.

**Comment by NaughtyZZ** [comment]
1. No. Registering is to formalize the data with a common template (same number of triangles and vertices in this case), while the corresponding vertex should share the same semantic meaning.
2. Yes. But it is a bit slow for so many faces in facescape and it requires manually labeled landmarks. I recommend to use the C++ program with initialization by the NICP method. In this way, you only need to replace the target face by the TU models (FaceScape) and run the *.exe demo.
3. It can be either marked by human or by algorithm automaticlly. If you use the TU models in FaceScape as initialization, the landmarks do not require to be marked.
I hope it will be helpful for you research. Thank you for attention.

**Comment by NaughtyZZ** [comment]
1. No. Registering is to formalize the data with a common template (same number of triangles and vertices in this case), while the corresponding vertex should share the same semantic meaning.
2. Yes. But it is a bit slow for so many faces in facescape. I recommend to use the C++ program with initialization by the NICP method. In this way, you only need to replace the target face by the TU models (FaceScape) and run the *.exe demo.
3.

**Comment by qaz8788817** [comment]
Ok. Thank you. Your guidance is very helpful to me.
